### ISSUE TITLE
[BUG] Ambient Sounds Placed Incorrectly in Firefox

### ISSUE THREAD

**Issue by patrickburk1988** [gsimon2/playlist-drag-and-drop#3]
I recently installed the module and discovered that it's functionally unusable in Firefox. This bug occurs whenever you drag a sound entity from the Playlists sidebar onto the canvas. Rather than dropping where you placed it, it is "thrown" randomly onto the scene — sometimes even off the edge of the map where you can see the radius but the sound itself can no longer be selected.

I can reproduce this bug with all other modules disabled. I'm on Windows 10 (64-bit), using Firefox version 89.0.2. I'm running Foundry version 0.8.8 on Forge, and my current module version is 1.1.0. For what it's worth, the module works perfectly in Chrome, so I'm assuming it's a browser-related issue.

**Comment by gsimon2** [comment]
Thanks for posting! I am primarily a chrome user so firefox probably slipped through my testing a bit. When I get some time I will dig into it and see if I can get it ironed out.

**Comment by gsimon2** [comment]
Looks like this is due to a "bug" that has been listed in Firefox for a number of years related to how they handle drag events. Either way I found a work around. Try out version `1.1.1` and feel free to re-open the issue if this does not resolve the problem for you. Thanks for posting!

**Comment by patrickburk1988** [comment]
Works like a charm! Thanks!
