### ISSUE TITLE
Feature Suggestion: Add optional key binding to activate drag 'n drop

### ISSUE THREAD

**Issue by deraviin** [gsimon2/playlist-drag-and-drop#5]
With many new playlist modules coming out, I am running into the issue of clicking on a track to use one of another modules features only for pdnd to activate and leave a track on the screen, sometimes out of bounds as well. 

I feel like the easiest solution is to create an optional key binding to actually use it for people using other modules like myself. Especially if the key binding can be customized.

**Comment by gsimon2** [comment]
I have added this capability to version `1.2.0`. Currently the only supported hotkey are CTRL, ALT, or CTRL+ALT as this was the thinnest slice of work. If this does not satisfy your requirements, feel free to re-open the issue. Thanks for posting!
